### ISSUE TITLE
dependency error with timm

### ISSUE THREAD

**Issue by sehandev** [MCG-NJU/EMA-VFI#3]
timm==0.6.11 needs torch version over 1.7.0

Can you tell me what version did you actually use?

**Comment by GuozhenZhang1999** [comment]
The actual version of torch we are using is 1.8.0. We deeply apologize for any confusion this may have caused and have already updated the README accordingly. Thank you very much for bringing this to our attention.

**Comment by sehandev** [comment]
Thanks!
