### ISSUE TITLE
About motion features

### ISSUE THREAD

**Issue by haonanhe** [MCG-NJU/EMA-VFI#7]
The first 3 elements of the motion feature list are empty []. Could you explain the reason for such a design? And the first 3 dims of motion features are 0, as shown below:

`def init_model_config(F=32, W=7, depth=[2, 2, 2, 4, 4]):
    '''This function should not be modified'''
    return { 
        'embed_dims':[F, 2*F, 4*F, 8*F, 16*F],
        'motion_dims':[0, 0, 0, 8*F//depth[-2], 16*F//depth[-1]],
        'num_heads':[8*F//32, 16*F//32],
        'mlp_ratios':[4, 4],`

Looking forward to your reply. Thanks.

**Comment by GuozhenZhang1999** [comment]
Thank you for your question. The first three correspond to convolutional neural networks, which are unable to extract or possess motion features. For more information, please refer to the third section of the paper.
